healthcheck_addr: "0.0.0.0:8080"

iperf_addr: "0.0.0.0:5001"

backends:
  - id: "srv-1"
    ip: "192.67.67.2:8080"
  - id: "srv-2"
    ip: "192.67.67.3:8080"

clusters:
  main-api:
    - "srv-1"
    - "srv-2"
  priority-api:
    - "srv-1"

rules:
  - clients:
      - "172.67.67.2/24:80"
    targets:
      - "main-api"
      - "priority-api"
    strategy:
      type: "Adaptive"
      coefficients: [ 1.5, 1.0, 0.5, 0.1 ]
      alpha: 0.75
